### ISSUE TITLE
Chunked Topics Don't Receive Numbered Topic Title Prefix

### ISSUE THREAD

**Issue by reifsnid** [dita-semia/org.dita-semia.topic-num#2]
Hi @PStellmann, thank you for creating and making this plugin available.

I'm very interested in using the plugin; however, I've noticed an issue with chunked topics that prevents me from using it and I'm hoping you're able to solve this issue.

In a ditamap, when a parent topic is set to @chunk="to-content", the topic and its children don't get the number topic title prefix added to their titles. However, the TOC still receives the topic title prefix. This leads me to believe it has something to do with the processTopic.xml, but since I'm still fairly new at XSLT I'm not sure.

Would you be willing to investigate this issue?

Thanks!

**Comment by PStellmann** [comment]
For testing I (temporarily) added a chunk="to-content" to one of the chapters of my test map and solved it for this scenario. Please test it with your files as well.

**Comment by reifsnid** [comment]
6143f85 resolves this issue.

I tested both my files and the test map, and it works as expected. 

Thank you!
