### ISSUE TITLE
Keydef and topicgroup are adding to the count

### ISSUE THREAD

**Issue by easirois** [dita-semia/org.dita-semia.topic-num#3]
Hello,

I'm using the Thunderbird sample content to test the plugin and ran into a couple of issues.  https://github.com/gnostyx/dita-demo-content-collection

It looks like keydefs and topicgroup are adding to the count. As well as topicrefs with toc="no".  Here is a similar example with your test submap.

```
<?xml version="1.0" encoding="UTF-8"?>
<map title="DITA Topic Map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="urn:oasis:names:tc:dita:xsd:map.xsd">
	<keydef keys="my-key" href="map-child-topic-1.dita"/>
	<topicgroup>
		<keydef href="some-funky-topic-1.dita" keys="my-awsome-key"/>
	</topicgroup>
	<topicref href="another-funky-topic-1.dita" toc="no"/>
	<topicref href="map-child-topic-1.dita">
		<topicref href="map-grandchild-topic-1.dita"/>
	</topicref>
	<topicref href="map-child-topic-2.dita"/>
</map>
```
To resolve the issue I need to add a couple of particles to the xpath that does the counting and a new variable to topicgroup (mapgroup-d/topicgroup). That so far seems to resolve the issue.  

```
<xsl:template match="*[contains(@class, $CLASS_TOPICREF)]" mode="GetTopicNum" as="xs:integer*">
	<xsl:apply-templates select="parent::*" mode="#current"/>
	<xsl:sequence select="count(preceding-sibling::*[contains(@class, $CLASS_TOPICREF)][not(@processing-role='resource-only')][not(contains(@class, $CLASS_TOPICGROUP))][not(@toc='no')]) + 1"/>
</xsl:template>

<xsl:variable name="CLASS_TOPICGROUP"		as="xs:string"	select="' mapgroup-d/topicgroup '"/>
```

**Comment by easirois** [comment]
I also added toc=no to the isTopicrefRelevant function:

<xsl:sequence select="(string($topicref/@href) != '') 
				and not($topicref/@processing-role = 'resource-only') 
				and not($topicref/@format = 'html')
				and not($topicref/@toc = 'no')
				and not($topicref/ancestor::*[contains(@class, $CLASS_RELTABLE)])"/>

**Comment by PStellmann** [comment]
Hi Eric,

your modifications seems reasonable to me - I simply didn't have these usecases, yet.

Without any testing I'm wondering:
1. The child topics from topicgroups are meant to me "lifted up" in the hiearchy. Your fix will just ignore those instead of counting them as well. But if this is no issue for you no need to invest the energy there.
2. An alternative way to ignore the keydefs would be to check for a non-empty href-attribute - which might handle additional contentless topicrefs as well. Or are you aware of any cases where this would not work?

Regards,
Patrik

**Comment by easirois** [comment]
Hi Patrik,

The big one is to ignore anything that is not supposed to add to the TOC. What was happening is that it would encounter one of those values and would skip it accordingly (adding the number in the TOC) but the next item would still have the next incremental number.  So map-child-topic-1.dita would have 4 as its initial value instead of "1".

Kind regards,
Eric

**Comment by easirois** [comment]
oops...didn't want to close the issue.

**Comment by PStellmann** [comment]
But topicgroups could also contain topics with a toc entry - so ignoring them completely would not always work.

I replaced the simple count() with a set of templates that should handle all kind of cases - including nested topicgroups.

**Comment by easirois** [comment]
Cool..Thanks.  I will give it a test.
