### ISSUE TITLE
Numbring in plain maps as root supported?

### ISSUE THREAD

**Issue by easirois** [dita-semia/org.dita-semia.topic-num#4]
Hi,

When trying to process the submap.ditamp as the root map the figures and tables aren't getting enumerated as is they were part of bookmap.  So two questions: 1) Are base maps supported?   2) If not, is there a technical limitation to their support?

**Comment by easirois** [comment]
essentially trying to get the same behaviour of a bookmap wrt to chapters.  Tables and figures have N-N format.

**Comment by PStellmann** [comment]
Hi,
I simply never used maps so as root structure. But the modification was no big deal an I just commited it. So please test it if it fits your need.

**Comment by easirois** [comment]
Perfect, thanks.  I added a second grand child toic to the submap (1-2) and the numbering came out as expect.  Much appreciated!

**Comment by easirois** [comment]
hmm..I'm get an error in my sample map that I've been using.  Let me see if I can simplify a test case.

D:\Ixiasoft\OG\kla-og\data\dita-ot-2.5.4\plugins\org.dita-semia.topic-num-master.orig\preprocess.topic-num.xml:97: Fatal error during transformation using D:\Ixiasoft\OG\kla-og\data\dita-ot-2.5.4\plugins\org.dita-semia.topic-num-master.orig\xsl\processMap.xsl: An empty sequence is not allowed as the value of variable $rootNum; SystemID: file:/D:/Ixiasoft/OG/kla-og/data/dita-ot-2.5.4/plugins/org.dita-semia.topic-num-master.orig/xsl/processTopic.xsl; Line#: 173; Column#: -1

**Comment by easirois** [comment]
This seems to work when I use
<xsl:when test="contains($numRootClass, $CLASS_CHAPTER) or $numRootClass = ' map/topicref '">

Otherwise, what is happening in my case is that the previous version is actually picking up the keydef instead of the actual topicref.  Ièll poke around a bit more.

**Comment by PStellmann** [comment]
A simple fix might be to make the variable rootNum as typ xs:integer**?** (line 212 in processTopic.xs). At least it will avoid the fatal error. Not sure if the numbering still works since I don't understand the actual setting that causes this situation.
If you can provide a sample use case I will take a look into it.

**Comment by easirois** [comment]
opps...missing the 'dash'  $numRootClass = '- map/topicref '

<keydef href="map-grandchild-topic-2.dita" keys="map-grandchild-topic-2"/>
        <topicref href="map-child-topic-1.dita">
		    <topicref href="map-grandchild-topic-1.dita"/>
	         <topicref keyref="map-grandchild-topic-2"/>
	  </topicref>
	  <topicref href="map-child-topic-2.dita"/>

It works fine with the href, but with keyref, the numbering is lost in this case. Where map-grandchild-topic-2 is just a copy of map-grandchild-topic-1.

**Comment by easirois** [comment]
Will try your suggestion

**Comment by easirois** [comment]
I'm good without keyref support.  That looks like a big change.

**Comment by easirois** [comment]
Another one to add to your list of things to ignore.  An empty topicref as in <topicref/>.  This template resolves the issue.  Otherwise, you get out of sequence numbers.

<xsl:template match="*[contains(@class, $CLASS_TOPICREF)][not(@href or @keyref)]" mode="GetLocalTopicNum" as="xs:integer?" priority="3">
		
		<xsl:apply-templates select="." mode="GetPrecLocalTopicNum"/>
	</xsl:template>

Edit: added keyref to not()  as well.
