### ISSUE TITLE
Support for topichead

### ISSUE THREAD

**Issue by easirois** [dita-semia/org.dita-semia.topic-num#5]
Hi,

Topichead adds info to the TOC, but do not have an associated @href.  So the numbering in the TOC gets messed up when one appears in a  map.  I have a pull request coming for this issue.  Just need to figure out how to associate things again.  It's been a while.

**Comment by easirois** [comment]
I have it working for a plain map, but when I use a bookmap, the numbering resets itself and adds "Chapter:" prefix.

**Comment by PStellmann** [comment]
The pull request worked fine. I only made some small modifications. Please check again with your real use-case if I didn't mess up anything.

**Comment by easirois** [comment]
Great, thank you. All is good. Closing.

**Comment by easirois** [comment]
Just one small fix to add.  
<xsl:variable name="rootNum" as="xs:integer"> --> <xsl:variable name="rootNum" as="xs:integer?"> in both instances in ProcessTopic.xsl.  Hit that one with a map that had navtitle element versus an attribute.

<topichead>
      <topicmeta>
         <navtitle>Preparation</navtitle>
      </topicmeta>
</topichead>

**Comment by PStellmann** [comment]
Could you please show an example of a map that causes a problem? Becaus making the value optional might avoid an error but I don't think the result will be correct. The following number formatting requires two numbers!?
And my tests with navtitle (within topicmeta) were alls successfull.

**Comment by easirois** [comment]
yes, let me see if I can replicate the issue with a smaller map.

**Comment by easirois** [comment]
ha...I can't seem to find the map in question at the moment.  I will dig through the sample maps in the project folder to find the one in question.

**Comment by easirois** [comment]
[sample-rootnum-issue.zip](https://github.com/dita-semia/org.dita-semia.topic-num/files/5716842/sample-rootnum-issue.zip)
Here is the sample map that produces a rootnum error.

D:\Ixiasoft\OG\data\dita-ot-2.5.4\plugins\org.dita-semia.topic-num\preprocess.topic-num.xml:97: Fatal error during transformation using D:\Ixiasoft\OG\data\dita-ot-2.5.4\plugins\org.dita-semia.topic-num\xsl\processMap.xsl: An empty sequence is not allowed as the value of variable $rootNum; SystemID: file:/D:/Ixiasoft/OG/data/dita-ot-2.5.4/plugins/org.dita-semia.topic-num/xsl/processTopic.xsl; Line#: 173; Column#: -1

**Comment by PStellmann** [comment]
I had to convert several topics to standard topic types to reproduce the error. :/

The reason for the error is the usage of keyrefs for topics. This was not handled, yet, so the atual topicref within the map could not be found.

I added support for it so you sample works fine now - as far I could see.

**Comment by easirois** [comment]
Sorry for the delay.  Works like a charm. Happy New Year.
